/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package piiiutscuaca.view;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author lndra
 */
public class akun extends javax.swing.JFrame {

    /** Creates new form Autentikasi */
    public akun() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JPasswordField();
        BtnSim = new javax.swing.JButton();
        btnPus = new javax.swing.JButton();
        btnBtl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel1.setText("Daftar akun");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama User");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Kata Sandi");

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1KeyPressed(evt);
            }
        });

        BtnSim.setText("SIMPAN");
        BtnSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimActionPerformed(evt);
            }
        });

        btnPus.setText("HAPUS");
        btnPus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPusActionPerformed(evt);
            }
        });

        btnBtl.setText("KELUAR");
        btnBtl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBtlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPus)
                        .addGap(38, 38, 38)
                        .addComponent(btnBtl)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPus)
                    .addComponent(btnBtl)
                    .addComponent(BtnSim))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimActionPerformed
        // TODO add your handling code here:
            String nama = txt1.getText();
            String sandi = txt2.getText();
         Connection con = new conek().getConnection();
        try{
            Statement statement = (Statement)con.createStatement();
            statement.executeUpdate("insert into t_user(NAMA_USR,KATA_SANDI) "+"values('"+nama+"','"+sandi+"')");
            statement.close();
            JOptionPane.showMessageDialog(rootPane, "Akun sudah tersimpan");
                txt1.setText("");
                txt2.setText("");
                txt1.requestFocus();
                              
                 }catch (Exception e){
                     JOptionPane.showMessageDialog(rootPane, "Gagal disimpan");
                     }
    
    }//GEN-LAST:event_BtnSimActionPerformed

    private void btnBtlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBtlActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBtlActionPerformed

    private void btnPusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPusActionPerformed
        // TODO add your handling code here:
        Connection con = new conek().getConnection();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin menghapus akun ini???", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (ok==0)
        try{
            Statement statement = (Statement)con.createStatement();
            statement.executeUpdate("delete from T_user where nama_usr='"+txt1+"'");
            statement.close();
            JOptionPane.showMessageDialog(rootPane, "Akun berhasil dihapus");
                txt1.setText("");
                txt2.setText("");
                txt1.requestFocus();
                              
                 }catch (Exception e){
                     JOptionPane.showMessageDialog(rootPane, "Akun gagal dihapus");
                     }
            
    }//GEN-LAST:event_btnPusActionPerformed

    private void txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyPressed
        // TODO add your handling code here:
        Connection con = new conek().getConnection();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             try
        {
            Statement statement = (Statement)con.createStatement();
            statement.executeQuery("select * from T_user where nama_usr='"+txt1+"'");
            con.createStatement();
            ResultSet rs = statement.executeQuery("select * from T_user where nama_usr='"+txt1+"'");
            //if (rs.next())
                
                while(rs.next()){
                    //txt1.setText(rs.getString("nama_usr"));
                    txt2.setText(rs.getString("KATA_SANDI"));
                }
        }catch(Exception e){
                
                }
        }
    }//GEN-LAST:event_txt1KeyPressed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
        Connection con = new conek().getConnection();
       // if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             try
        {
            Statement statement = (Statement)con.createStatement();
            statement.executeQuery("select * from T_user where nama_usr='"+txt1+"'");
            con.createStatement();
            ResultSet rs = statement.executeQuery("select * from T_user where nama_usr='"+txt1+"'");
            //if (rs.next())
                
                while(rs.next()){
                    //txt1.setText(rs.getString("nama_usr"));
                    txt2.setText(rs.getString("KATA_SANDI"));
                }
        }catch(Exception e){
                
                }
        
    }//GEN-LAST:event_txt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new akun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSim;
    private javax.swing.JButton btnBtl;
    private javax.swing.JButton btnPus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt1;
    private javax.swing.JPasswordField txt2;
    // End of variables declaration//GEN-END:variables

}
