/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piiiutscuaca.view;
//import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;


/**
 *
 * @author lndra
 */
public class flogin extends javax.swing.JFrame {

    /**
     * Creates new form flogin
     */
    public flogin() {
        initComponents();
    }

    flogin(FrmCuaca aThis, boolean rootPaneCheckingEnabled) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        BtnKonek = new javax.swing.JButton();
        txtPsw = new javax.swing.JPasswordField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("KONEKSI DATABASE");

        jLabel2.setText("Nama User");

        jLabel3.setText("Password");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        BtnKonek.setText("KONEKSIKAN");
        BtnKonek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKonekActionPerformed(evt);
            }
        });
        BtnKonek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKonekKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnKonek)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txtPsw)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(BtnKonek)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void BtnKonekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKonekActionPerformed
        // TODO add your handling code here:
        //String cnkUserName= txtNama.getText();
        //String cnkpasw= txtPsw.getText();
        //conek c = new conek(cnkUserName, cnkpasw);
        Connection con = new conek().getConnection();
        try{
            Statement statement = (Statement)con.createStatement();
            ResultSet result=statement.executeQuery("select * from t_cuaca");
            if(txtNama.getText().equals("root")){
                if(txtPsw.getText().equals("manonjaya")){
                    JOptionPane.showMessageDialog(null, "Koneksi ke Database BERHASIL");
                    new FrmCuaca().show();
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Password tidak sesuai");
                    JOptionPane.showMessageDialog(null, "Koneksi ke Database GAGAL");
                    txtPsw.setText("");
                    txtNama.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(rootPane,"User tidak ditemukan");
                    //txtNama.setText("");
                    txtPsw.setText("");
                    txtNama.requestFocus();
            }
            if(txtNama.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Coba login kembali");
         
            }
            
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_BtnKonekActionPerformed

    private void BtnKonekKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKonekKeyPressed
        // TODO add your handling code here:
        Connection con = new conek().getConnection();
        try{
            Statement statement = (Statement)con.createStatement();
            ResultSet result=statement.executeQuery("select * from t_cuaca");
            if(txtNama.getText().equals("root")){
                if(txtPsw.getText().equals("manonjaya")){
                    JOptionPane.showMessageDialog(null, "Koneksi ke Database BERHASIL");
                    new FrmCuaca().show();
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Password tidak sesuai");
                    JOptionPane.showMessageDialog(null, "Koneksi ke Database GAGAL");
                    txtPsw.setText("");
                    txtNama.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(rootPane,"User tidak ditemukan");
                    //txtNama.setText("");
                    txtPsw.setText("");
                    txtNama.requestFocus();
            }
            if(txtNama.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Coba login kembali");
         
            }
            
        }catch (Exception e){
            
        }

    }//GEN-LAST:event_BtnKonekKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnKonek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPsw;
    // End of variables declaration//GEN-END:variables
}
