/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piiiutscuaca.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lndra
 */
public class Kolom extends javax.swing.JFrame {

    /**
     * Creates new form Kolom
     */
    private DefaultTableModel bagan;
    public hpus fAB = null;
    
    public Kolom() {
        initComponents();
        bagan = new DefaultTableModel();
        tblDat.setModel(bagan);
        bagan.addColumn("Tanggal");
        bagan.addColumn("Nama Kota");
        bagan.addColumn("Suhu");
        bagan.addColumn("Suhu Maks");
        bagan.addColumn("Suhu Min");
        bagan.addColumn("Kecepatan Angin");
        bagan.addColumn("Kelembapan");
        bagan.addColumn("Tekanan Udara");
        
    }

    Kolom(Object object, boolean closable) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    public boolean isCellEditable(int rowIndex, int colIndex){
            return false;
            
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnTampl = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDat);

        jLabel1.setText("Nama Kota :");

        btnTampl.setText("Tampilkan");
        btnTampl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamplActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTampl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTampl)
                    .addComponent(btnKeluar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTamplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamplActionPerformed
        // TODO add your handling code here:
        Connection con = new conek().getConnection();
        
        bagan.getDataVector().removeAllElements();
        bagan.fireTableDataChanged();
        
             try
        {
            Statement statement = (Statement)con.createStatement();
            statement.executeQuery("select * from t_cuaca where nama_kota='"+txtNama.getText()+"'");
            con.createStatement();
            ResultSet rs = statement.executeQuery("select * from t_cuaca where nama_kota='"+txtNama.getText()+"'");
            
            while(rs.next()){
                Object[]obj = new Object[8];
                obj[0]= rs.getString("date");
                obj[1]= rs.getString("nama_kota");
                obj[2]= rs.getString("suhu");
                obj[3]= rs.getString("suhu_maks");
                obj[4]= rs.getString("suhu_min");
                obj[5]= rs.getString("kecepatan_angin");
                obj[6]= rs.getString("kelembapan");
                obj[7]= rs.getString("tekanan_udara");
                
                bagan.addRow(obj);
                
                }
            rs.close();
            statement.close();
        }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "gagal konek");
                    }
             if(txtNama.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Masukkan Nama Kota yang Ingin di Tampilkan","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnTamplActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tblDatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatMouseClicked
        // TODO add your handling code here:
        int bagan = tblDat.getSelectedRow();
        fAB.namKota = tblDat.getValueAt(bagan,1).toString();
        fAB.suhu = tblDat.getValueAt(bagan,2).toString();
        fAB.suhu_mak = tblDat.getValueAt(bagan,3).toString();
        fAB.suhu_min = tblDat.getValueAt(bagan,4).toString();
        fAB.kecAngin = tblDat.getValueAt(bagan,5).toString();
        fAB.lembap = tblDat.getValueAt(bagan,6).toString();
        fAB.tekan = tblDat.getValueAt(bagan,7).toString();
        fAB.itemTerpilih();
        this.dispose();
        //fAB.namKota = (tblDat.getValueAt(tblDat.getSelectedRow(),0).toString());
        //jTextField2.setText(tblDat.getValueAt(tblDat.getSelectedRow(),2).toString());
        //jTextField3.setText(tblDat.getValueAt(tblDat.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tblDatMouseClicked

    public void hps(){
        Connection con = new conek().getConnection();
        Statement stat;
        if(tblDat.getSelectedRow()<0){
            JOptionPane.showMessageDialog(this, "Pilih salah satu data pada tabel","Perhatian",JOptionPane.WARNING_MESSAGE);
        }else {
            try{
                Statement statement = (Statement)con.createStatement();
                statement.executeQuery("delete from T_CUACA where nama_kota=?");
                con.createStatement();
                ResultSet rs = statement.executeQuery("delete from T_CUACA where nama_kota=?");
               
            
            }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "gagal konek");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kolom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kolom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kolom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kolom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kolom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTampl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDat;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
